##
## EPITECH PROJECT, 2024
## ARCADE
## File description:
## Graphicals Makefile
##

all: ncurses sdl2

ncurses:
	make -C NCurses

sdl2:
	make -C SDL2

clean:
	make -C NCurses clean
	make -C SDL2 clean

fclean:
	make -C NCurses fclean
	make -C SDL2 fclean

re: fclean all
