name: ci-arcade

env:
  MIRROR_URL: git@github.com:EpitechPromo2027/B-OOP-400-NAN-4-1-arcade-alban.peralta.git
  EXECUTABLES: "./arcade,./lib/arcade_ncurses.so,./lib/arcade_sdl2.so"

on:
  push:
    branches-ignore:
      - ga-ignore-**
  pull_request:
    branches-ignore:
      - ga-ignore-**

jobs:
  check_program_compilation:
    name: Check program compilation
    needs: check_interfaces
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker:latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Check compilation
        run: make
        timeout-minutes: 2
      - name: Check executables
        run: |
          IFS=','
          string="${{ env.EXECUTABLES }}"
          for exec in $string; do
            if ! [ -x "$exec" ] || ! [ -f "$exec" ]; then
              exit 42
            fi
          done
      - name: Check clean
        run: make clean
  push_to_mirror:
    name: Push to mirror
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: check_program_compilation
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ${{ env.MIRROR_URL }}
          ssh_private_key:
            ${{ secrets.GIT_SSH_PRIVATE_KEY }}
  check_submodules:
    name: Check submodules
    container:
      image: epitechcontent/epitest-docker:latest
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Check submodules
        run: |
          make check-submodules
          if [ $? -eq 1 ]; then
              exit 1
          fi